apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: account
        version: v1
    spec:
      containers:
      - name: account
        image: hemantseth0210/account
        ports:
        - name: http
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  selector:
    app: account
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---